
[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "deutsch-jozsa-noise"
version = "0.0.1"
description = "Deutsch–Jozsa algorithm noise analysis and quantum computing toolkit"
readme = "README.md"
requires-python = ">=3.9"

dependencies = [
    "numpy",
    "scipy",
    "matplotlib",
    "ipython",
    "ipywidgets",
    "notebook<7",
    "qutip",
]

[project.optional-dependencies]
test = [
    "pytest",
    "pytest-cov",
    "nbconvert",
]

[tool.setuptools]
package-dir = {"" = "src"}

[tool.setuptools.packages.find]
where = ["src"]

[tool.coverage.run]
omit = [
    "*/tests/*",
    "*/src/quantum_algorithms/__init__.py", 
]